version = 1

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/at-en/nmap"

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "11"

[[analyzers]]
name = "cxx"

[[analyzers]]
name = "csharp"